[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.123.4",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "pytrends>=4.9.2",
    "uvicorn>=0.38.0",
]
